apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: mysql
        image: 897193292353.dkr.ecr.us-east-1.amazonaws.com/docker-assignment:v1.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: pwd
          - name: MYSQL_DATABASE
            value: employees
        ports:
        - containerPort: 3306
          protocol: TCP
