apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app.kubernetes.io/name: app
    app.kubernetes.io/component: frontend
