apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: sqldb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 132456686334.dkr.ecr.us-east-1.amazonaws.com/mysql-img:mysql_version_1
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: pwd
          - name: MYSQL_DATABASE
            value: employees
          ports:
            - containerPort: 3306
