apiVersion: v1
kind: Pod
metadata:
  name: pod-mysql
  namespace: nik-db
  labels:
    app: mysql
spec:
  containers:
    - name: mysql   
      image: 132456686334.dkr.ecr.us-east-1.amazonaws.com/mysql-img:mysql_version_1
      env:
          - name: MYSQL_ROOT_PASSWORD
            value: pwd
          - name: MYSQL_DATABASE
            value: employees    
      ports:
        - containerPort: 3306
