apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: nik-db
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
