apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-v2
  namespace: employees
  labels:
    app: webapp
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      version: v2
  template:
    metadata:
      labels:
        app: webapp
        version: v2
    spec:
      containers:
      - name: app
        image: 897193292353.dkr.ecr.us-east-1.amazonaws.com/docker-assignment:v0.1
        env:
        - name: DBHOST
          value: 10.96.75.170 
        - name: DBUSER
          value: root
        - name: DBPWD
          value: pwd
        - name: DATABASE
          value: employees
        - name: APP_COLOR
          value: green
        ports:
        - containerPort: 8080
