apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp
  labels:
    app: webapp
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      version: v1
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
      containers:
        - name: websrv-img
          image: 132456686334.dkr.ecr.us-east-1.amazonaws.com/websrv-img:webserver_version_1
          env:
            - name: DBPWD
              value: "12345"
            - name: DBUSER
              value: root
            - name: DBHOST
              value: "mysql-service.sqldb.svc.cluster.local"
            - name: DBPORT
              value: "3306"
          ports:
            - containerPort: 8080
