apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: nik-app
  labels:
    app: webapp
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      version: v1
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
       containers:
      - name: app
        image: 137816499949.dkr.ecr.us-east-1.amazonaws.com/week10-dev-repository:app-v0.1
        env:
        - name: DBHOST
          value: 10.96.220.119 
        - name: DBUSER
          value: root
        - name: DBPWD
          value: pwd
        - name: DATABASE
          value: employees
        - name: APP_COLOR
          value: blue
        ports:
        - containerPort: 8080
