apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: nik-app
spec:
  containers:
  - name: app
    image: 137816499949.dkr.ecr.us-east-1.amazonaws.com/week10-dev-repository:app-v0.1
    env:
    - name: DBHOST
      value: 10.96.75.170 
    - name: DBUSER
      value: root
    - name: DBPWD
      value: pwd
    - name: DATABASE
      value: employees
    - name: APP_COLOR
      value: blue
  ports:
  - containerPort: 8080

