apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp
  labels:
    app: webapp
    version: v1
spec:
  type: NodePort
  selector:
    app: webapp
    version: v1
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
