apiVersion: v1
kind: Service
metadata:
  name: webapp-service-v2
  namespace: employees
  labels:
    app: webapp
    version: v2
spec:
  type: NodePort
  selector:
    app: webapp
    version: v2
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
